import React, { useState } from 'react';
import { SalesItem, LaborItem, Language } from '../types';
import { generateVariancePDF, exportVarianceCSV } from '../lib/pdfGenerator';
import {
  X,
  Download,
  Printer,
  Copy,
  Check,
  FileSpreadsheet,
  FileJson,
  FileText,
  Loader2,
  CheckCircle2,
  AlertCircle,
} from 'lucide-react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  salesData: SalesItem[];
  laborData: LaborItem[];
  language: Language;
  isSimulated?: boolean;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  salesData,
  laborData,
  language,
  isSimulated = false,
}) => {
  const [copied, setCopied] = useState(false);
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);
  const [pdfSuccess, setPdfSuccess] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleDownloadPDF = async () => {
    try {
      setIsGeneratingPDF(true);
      setErrorMessage(null);
      await generateVariancePDF(salesData, laborData, language, isSimulated);
      setPdfSuccess(true);
      setTimeout(() => setPdfSuccess(false), 3000);
    } catch (err: any) {
      console.error('PDF generation error:', err);
      setErrorMessage(
        language === 'uk'
          ? 'Помилка при формуванні PDF. Спробуйте завантажити CSV або скопіювати звіт.'
          : 'Failed to generate PDF. Try downloading CSV or copying report text.'
      );
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  const handleDownloadCSV = () => {
    try {
      exportVarianceCSV(salesData, laborData, language);
    } catch (err) {
      console.error('CSV export error:', err);
    }
  };

  const handlePrint = () => {
    try {
      window.print();
    } catch (e) {
      console.warn('Direct print blocked by iframe environment:', e);
    }
  };

  const handleCopySummary = () => {
    const totalPlanSales = salesData.reduce((acc, item) => acc + (item.planTotal ?? 0), 0);
    const totalFactSales = salesData.reduce((acc, item) => acc + (item.factTotal ?? 0), 0);
    const totalPlanLabor = laborData.reduce((acc, item) => acc + (item.planTotal ?? 0), 0);
    const totalFactLabor = laborData.reduce((acc, item) => acc + (item.factTotal ?? 0), 0);
    const salesVariance = totalFactSales - totalPlanSales;
    const laborVariance = totalFactLabor - totalPlanLabor;

    const summary = `=== ФІНАНСОВИЙ ЗВІТ / FINANCIAL VARIANCE REPORT ===\n
ПРОДАЖІ (SALES):
- План виручки: ${totalPlanSales.toLocaleString()} ₴
- Факт виручки: ${totalFactSales.toLocaleString()} ₴
- Відхилення: ${salesVariance.toLocaleString()} ₴ (${totalPlanSales > 0 ? ((salesVariance / totalPlanSales) * 100).toFixed(1) : 0}%)
- Вплив фактору обсягу (ΔQ): ${salesData.reduce((acc, i) => acc + (i.varianceVolume ?? 0), 0).toLocaleString()} ₴
- Вплив фактору ціни (ΔP): ${salesData.reduce((acc, i) => acc + (i.variancePrice ?? 0), 0).toLocaleString()} ₴

ВИРОБНИЦТВО ТА ПРАЦЯ (LABOR):
- План витрат: ${totalPlanLabor.toFixed(1)} ₴/т
- Факт витрат: ${totalFactLabor.toFixed(1)} ₴/т
- Відхилення (перевитрати): +${laborVariance.toFixed(1)} ₴/т (${totalPlanLabor > 0 ? ((laborVariance / totalPlanLabor) * 100).toFixed(1) : 0}%)

Generated by Enterprise Variance Controller.`;

    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownloadJSON = () => {
    const data = {
      timestamp: new Date().toISOString(),
      status: isSimulated ? 'simulated' : 'baseline',
      sales: salesData,
      labor: laborData,
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `variance_data_${new Date().toISOString().slice(0, 10)}.json`;
    link.click();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-xs animate-fade-in">
      <div className="bg-white border border-[#E2E8F0] rounded-2xl max-w-xl w-full p-6 shadow-2xl space-y-5">
        <div className="flex items-center justify-between border-b border-[#F1F5F9] pb-4">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-[#EFF6FF] text-[#3B82F6] flex items-center justify-center">
              <Download className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-[#0F172A]">
                {language === 'uk' ? 'Експорт та завантаження звіту' : 'Export & Download Report'}
              </h3>
              <p className="text-xs text-[#64748B]">
                {language === 'uk'
                  ? 'Офіційний PDF-звіт, Excel/CSV таблиця або сирі дані'
                  : 'Official PDF document, Excel/CSV tables, or raw data'}
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-lg text-[#94A3B8] hover:text-[#0F172A] hover:bg-[#F1F5F9] transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {errorMessage && (
          <div className="p-3 bg-red-50 border border-red-200 rounded-xl text-xs text-red-700 flex items-center gap-2">
            <AlertCircle className="w-4 h-4 shrink-0 text-red-500" />
            <span>{errorMessage}</span>
          </div>
        )}

        {/* Primary PDF Download Banner */}
        <div className="bg-[#EFF6FF] border border-[#BFDBFE] rounded-xl p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="space-y-0.5">
            <div className="flex items-center gap-1.5">
              <span className="text-xs font-bold text-[#1E3A8A] flex items-center gap-1">
                <FileText className="w-4 h-4 text-[#2563EB]" />
                {language === 'uk' ? 'Офіційний PDF-звіт (A4)' : 'Official PDF Document (A4)'}
              </span>
              <span className="px-1.5 py-0.2 bg-[#DBEAFE] text-[#1D4ED8] text-[10px] font-bold rounded">
                PDF
              </span>
            </div>
            <p className="text-[11px] text-[#3B82F6]">
              {language === 'uk'
                ? 'Містить підсумкові KPI, таблиці продажів і праці, фактори ΔQ/ΔP та висновки'
                : 'Complete with KPI cards, sales & labor tables, factor bridge, and sign-offs'}
            </p>
          </div>

          <button
            id="download-pdf-btn"
            type="button"
            disabled={isGeneratingPDF}
            onClick={handleDownloadPDF}
            className={`px-4 py-2.5 rounded-xl text-xs font-bold text-white shadow-xs flex items-center justify-center gap-2 transition-all shrink-0 cursor-pointer ${
              pdfSuccess
                ? 'bg-[#10B981] hover:bg-[#059669]'
                : isGeneratingPDF
                ? 'bg-[#60A5FA] cursor-wait'
                : 'bg-[#2563EB] hover:bg-[#1D4ED8]'
            }`}
          >
            {isGeneratingPDF ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin text-white" />
                <span>{language === 'uk' ? 'Генерація PDF...' : 'Creating PDF...'}</span>
              </>
            ) : pdfSuccess ? (
              <>
                <CheckCircle2 className="w-4 h-4 text-white" />
                <span>{language === 'uk' ? 'Завантажено!' : 'Downloaded!'}</span>
              </>
            ) : (
              <>
                <Download className="w-4 h-4 text-white" />
                <span>{language === 'uk' ? 'Завантажити PDF' : 'Download PDF'}</span>
              </>
            )}
          </button>
        </div>

        {/* Secondary Formats Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          {/* Excel / CSV */}
          <button
            id="download-csv-btn"
            type="button"
            onClick={handleDownloadCSV}
            className="p-3.5 rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] hover:bg-white hover:border-[#CBD5E1] text-left transition-all space-y-1.5 shadow-xs cursor-pointer group"
          >
            <div className="flex items-center justify-between">
              <FileSpreadsheet className="w-5 h-5 text-[#10B981]" />
              <span className="text-[10px] font-bold text-[#10B981] bg-[#ECFDF5] px-1.5 py-0.5 rounded border border-[#A7F3D0]">
                .CSV
              </span>
            </div>
            <span className="text-xs font-bold text-[#0F172A] block group-hover:text-[#2563EB] transition-colors">
              {language === 'uk' ? 'Таблиця Excel' : 'Excel / CSV'}
            </span>
            <span className="text-[11px] text-[#64748B] block leading-tight">
              {language === 'uk' ? 'Готові таблиці з формулами' : 'Raw structured tables for Excel'}
            </span>
          </button>

          {/* JSON */}
          <button
            id="download-json-btn"
            type="button"
            onClick={handleDownloadJSON}
            className="p-3.5 rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] hover:bg-white hover:border-[#CBD5E1] text-left transition-all space-y-1.5 shadow-xs cursor-pointer group"
          >
            <div className="flex items-center justify-between">
              <FileJson className="w-5 h-5 text-[#8B5CF6]" />
              <span className="text-[10px] font-bold text-[#8B5CF6] bg-[#F5F3FF] px-1.5 py-0.5 rounded border border-[#DDD6FE]">
                .JSON
              </span>
            </div>
            <span className="text-xs font-bold text-[#0F172A] block group-hover:text-[#2563EB] transition-colors">
              {language === 'uk' ? 'Структура JSON' : 'Raw JSON'}
            </span>
            <span className="text-[11px] text-[#64748B] block leading-tight">
              {language === 'uk' ? 'Для розробників та систем' : 'For integration & databases'}
            </span>
          </button>

          {/* Direct Print */}
          <button
            id="print-report-btn"
            type="button"
            onClick={handlePrint}
            className="p-3.5 rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] hover:bg-white hover:border-[#CBD5E1] text-left transition-all space-y-1.5 shadow-xs cursor-pointer group"
          >
            <div className="flex items-center justify-between">
              <Printer className="w-5 h-5 text-[#64748B]" />
              <span className="text-[10px] font-bold text-[#64748B] bg-[#F1F5F9] px-1.5 py-0.5 rounded border border-[#E2E8F0]">
                Ctrl+P
              </span>
            </div>
            <span className="text-xs font-bold text-[#0F172A] block group-hover:text-[#2563EB] transition-colors">
              {language === 'uk' ? 'Друк сторінки' : 'Print Browser'}
            </span>
            <span className="text-[11px] text-[#64748B] block leading-tight">
              {language === 'uk' ? 'Через системний діалог друку' : 'Via system print dialog'}
            </span>
          </button>
        </div>

        {/* Footer Actions */}
        <div className="pt-3 border-t border-[#F1F5F9] flex items-center justify-between">
          <button
            id="copy-summary-btn"
            type="button"
            onClick={handleCopySummary}
            className="px-3.5 py-2 text-xs font-semibold rounded-lg bg-white hover:bg-[#F8FAFC] text-[#334155] border border-[#E2E8F0] flex items-center gap-1.5 transition-colors shadow-xs cursor-pointer"
          >
            {copied ? <Check className="w-4 h-4 text-[#10B981]" /> : <Copy className="w-4 h-4 text-[#64748B]" />}
            <span>
              {copied
                ? language === 'uk'
                  ? 'Скопійовано!'
                  : 'Copied!'
                : language === 'uk'
                ? 'Копіювати текстовий дайджест'
                : 'Copy Text Summary'}
            </span>
          </button>

          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 text-xs font-semibold rounded-lg bg-[#0F172A] hover:bg-[#1E293B] text-white transition-colors cursor-pointer"
          >
            {language === 'uk' ? 'Закрити' : 'Close'}
          </button>
        </div>
      </div>
    </div>
  );
};

